// templates/design/shadcn/react-router/files/app/components/ui/label.tsx
import * as React from 'react'
import * as LabelPrimitive from '@radix-ui/react-label'

import { cn } from '~/lib/utils'

function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}

export { Label }

// templates/design/tailwind/sveltekit/files/src/lib/components/ui/label.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { cn } from '$lib/utils'

  type Props = {
    class?: string
    for?: string
    children?: Snippet
  }

  let { class: className = '', for: htmlFor, children }: Props = $props()
</script>

<label
  for={htmlFor}
  data-slot="label"
  class={cn(
    'flex select-none items-center gap-2 text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
    className,
  )}
>
  {#if children}{@render children()}{/if}
</label>
