// templates/design/daisyui/react-router/files/app/components/ui/input.tsx
import * as React from 'react'

import { cn } from '~/lib/utils'

function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn('input w-full', className)}
      {...props}
    />
  )
}

export { Input }

// templates/design/daisyui/sveltekit/files/src/lib/components/ui/input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'
  import { cn } from '$lib/utils'

  type Props = HTMLInputAttributes & { class?: string }

  let {
    class: className = '',
    value = $bindable(''),
    type = 'text',
    ...rest
  }: Props = $props()
</script>

<input
  bind:value
  {type}
  data-slot="input"
  class={cn('input w-full', className)}
  {...rest}
/>
